/**
 * Smartsheet integration service.
 *
 * Wraps the Smartsheet REST API (via smartsheet-javascript-sdk) to create and
 * update project timeline sheets. Timeline task rows are generated by calling
 * the configured AI provider (Anthropic or OpenAI).
 */

import * as smartsheetLib from "smartsheet";
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { getSmartsheetKey, getAnthropicKey, getOpenAIKey } from "./secrets";
import type { Project } from "../shared/schema";

// Column titles for the timeline sheet
const COLUMN_TITLES = [
  "Task Name",
  "Phase",
  "Start Date",
  "End Date",
  "Duration (days)",
  "Owner",
  "Status",
  "Notes",
] as const;

export interface TimelineTask {
  taskName: string;
  phase: string;
  startDate: string;
  endDate: string;
  durationDays: number;
  owner: string;
  status: string;
  notes: string;
}

export interface TimelineResult {
  sheetId: string;
  sheetUrl: string;
}

function getClient() {
  const key = getSmartsheetKey();
  if (!key) throw new Error("Smartsheet API key not configured");
  return smartsheetLib.createClient({ accessToken: key, logLevel: "info" });
}

/** Verify the API key by fetching the current user. Returns email on success. */
export async function verifySmartsheetConnection(): Promise<{ connected: boolean; email?: string; error?: string }> {
  try {
    const client = getClient();
    const result = await client.users.getCurrentUser({});
    const user = (result as any).data ?? result;
    return { connected: true, email: user.email };
  } catch (err: any) {
    return { connected: false, error: err?.message ?? "Unknown error" };
  }
}

/** Generate timeline tasks using the configured AI provider. */
export async function generateTimelineTasks(
  project: Project,
  settings: { provider?: string | null }
): Promise<TimelineTask[]> {
  const prompt = buildTimelinePrompt(project);

  let raw: string;
  if (settings.provider === "anthropic") {
    const key = getAnthropicKey();
    if (!key) throw new Error("Anthropic API key not configured");
    const client = new Anthropic({ apiKey: key, timeout: 60_000 });
    const msg = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }],
    });
    raw = (msg.content[0] as { type: string; text: string }).text;
  } else {
    const key = getOpenAIKey();
    if (!key) throw new Error("OpenAI API key not configured");
    const client = new OpenAI({ apiKey: key, timeout: 60_000 });
    const resp = await client.chat.completions.create({
      model: "gpt-5.2",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
    });
    raw = resp.choices[0].message.content ?? "{}";
  }

  return parseTasksFromResponse(raw);
}

function buildTimelinePrompt(project: Project): string {
  const milestones = (project.billingMilestones as { stage: string; percentage: number; date: string }[])
    .map((m) => `  - ${m.stage} (${m.percentage}%): ${m.date}`)
    .join("\n");
  const owners = (project.flipsideStakeholders as { name: string; role: string }[])
    .map((s) => `  - ${s.name} (${s.role})`)
    .join("\n");

  return `You are a project management expert. Generate a detailed project timeline as a JSON array of tasks.

Project details:
- Name: ${project.projectName}
- Type: ${project.projectType}
- Size: ${project.projectSize}
- Start date: ${project.startDate}
- End date: ${project.endDate}
- Summary: ${project.summary}

Billing milestones (use as phase anchors):
${milestones}

Team members available to assign as owners:
${owners}

Return a JSON object with a single key "tasks" containing an array. Each task must have exactly these fields:
{
  "taskName": "string (concise action-oriented task name)",
  "phase": "string (phase name aligned to billing milestones)",
  "startDate": "YYYY-MM-DD",
  "endDate": "YYYY-MM-DD",
  "durationDays": number,
  "owner": "string (first name only from the team list, or 'TBC')",
  "status": "Not Started",
  "notes": "string (brief context, or empty string)"
}

Guidelines:
- Generate 15–30 tasks appropriate for a ${project.projectType} project of ${project.projectSize} size
- Group tasks into phases that align with the billing milestones
- Assign realistic start/end dates between ${project.startDate} and ${project.endDate}
- Assign owners sensibly based on their role
- All dates must be in YYYY-MM-DD format
- Return only valid JSON, no markdown, no explanation`;
}

function parseTasksFromResponse(raw: string): TimelineTask[] {
  // Strip markdown code fences if present
  const cleaned = raw.replace(/^```(?:json)?\n?/m, "").replace(/\n?```$/m, "").trim();
  const parsed = JSON.parse(cleaned);
  const arr = Array.isArray(parsed) ? parsed : (parsed.tasks ?? []);
  return arr.map((t: Record<string, unknown>) => ({
    taskName: String(t.taskName ?? t.task_name ?? ""),
    phase: String(t.phase ?? ""),
    startDate: String(t.startDate ?? t.start_date ?? ""),
    endDate: String(t.endDate ?? t.end_date ?? ""),
    durationDays: Number(t.durationDays ?? t.duration_days ?? 0),
    owner: String(t.owner ?? "TBC"),
    status: String(t.status ?? "Not Started"),
    notes: String(t.notes ?? ""),
  }));
}

/**
 * Create a new timeline sheet in Smartsheet.
 * If workspaceId is provided, the sheet is created inside that workspace.
 */
export async function createTimelineSheet(
  project: Project,
  tasks: TimelineTask[],
  workspaceId?: string | null
): Promise<TimelineResult> {
  const client = getClient();
  const sheetName = `${project.sheetRef} - ${project.projectName} Timeline`;

  // Build column definitions
  const columns = COLUMN_TITLES.map((title, i) => ({
    title,
    type: "TEXT_NUMBER" as const,
    primary: i === 0,
  }));

  let sheet: any;
  if (workspaceId) {
    sheet = await client.workspaces.createSheetInWorkspace({
      workspaceId,
      body: { name: sheetName, columns },
    });
  } else {
    sheet = await client.sheets.createSheet({ body: { name: sheetName, columns } });
  }

  const sheetId: string = String(sheet.result?.id ?? sheet.id);

  // Fetch the sheet to get column IDs
  const sheetDetails = await client.sheets.getSheet({ id: sheetId });
  const colIds: number[] = (sheetDetails.columns ?? []).map((c: any) => c.id);

  await writeTaskRows(client, sheetId, colIds, tasks);

  // Retrieve the permalink
  const finalSheet = await client.sheets.getSheet({ id: sheetId });
  const sheetUrl: string = finalSheet.permalink ?? `https://app.smartsheet.com/sheets/${sheetId}`;

  return { sheetId, sheetUrl };
}

/**
 * Update an existing timeline sheet by replacing all data rows.
 */
export async function updateTimelineSheet(
  sheetId: string,
  tasks: TimelineTask[]
): Promise<void> {
  const client = getClient();

  // Get current rows and column IDs
  const sheet = await client.sheets.getSheet({ id: sheetId });
  const colIds: number[] = (sheet.columns ?? []).map((c: any) => c.id);
  const existingRows: any[] = sheet.rows ?? [];

  // Delete all existing rows
  if (existingRows.length > 0) {
    const rowIds = existingRows.map((r: any) => r.id);
    // Smartsheet delete accepts up to 450 row IDs at a time
    for (let i = 0; i < rowIds.length; i += 450) {
      await client.sheets.deleteRows({
        sheetId,
        body: { ids: rowIds.slice(i, i + 450) },
      });
    }
  }

  await writeTaskRows(client, sheetId, colIds, tasks);
}

async function writeTaskRows(
  client: ReturnType<typeof smartsheetLib.createClient>,
  sheetId: string,
  colIds: number[],
  tasks: TimelineTask[]
): Promise<void> {
  if (tasks.length === 0) return;

  const rows = tasks.map((task) => ({
    toBottom: true,
    cells: [
      { columnId: colIds[0], value: task.taskName },
      { columnId: colIds[1], value: task.phase },
      { columnId: colIds[2], value: task.startDate },
      { columnId: colIds[3], value: task.endDate },
      { columnId: colIds[4], value: task.durationDays },
      { columnId: colIds[5], value: task.owner },
      { columnId: colIds[6], value: task.status },
      { columnId: colIds[7], value: task.notes },
    ].filter((_, i) => colIds[i] !== undefined),
  }));

  // Add up to 500 rows at a time
  for (let i = 0; i < rows.length; i += 500) {
    await client.sheets.addRows({
      sheetId,
      body: rows.slice(i, i + 500),
    });
  }
}
