/**
 * Smartsheet integration service.
 *
 * Wraps the Smartsheet REST API (via smartsheet-javascript-sdk) to create and
 * update project timeline sheets. Timeline task rows are generated by calling
 * the configured AI provider (Anthropic or OpenAI).
 *
 * Sheet structure:
 *   - Phase header rows (parent, bold) group tasks visually
 *   - Task rows are children of their phase header
 *   - Columns: Task Name | Start Date | End Date | Duration (days) | Predecessor | Owner | Status | Notes
 *   - Project settings enable Gantt / dependency tracking
 */

import * as smartsheetLib from "smartsheet";
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { getSmartsheetKey, getAnthropicKey, getOpenAIKey } from "./secrets";
import type { Project } from "../shared/schema";

// Column definitions for new sheets.
// NOTE: Do NOT include a Predecessor column here — Smartsheet automatically
// adds a system-managed "Predecessor" column when project settings are enabled.
// NOTE: Do NOT include a Duration column — Smartsheet adds its own system
// "Duration" column when dependencies/Gantt are enabled, causing duplicates.
const COLUMNS = [
  { title: "Task Name",  type: "TEXT_NUMBER", primary: true  },
  { title: "Start Date", type: "DATE",        primary: false },
  { title: "End Date",   type: "DATE",        primary: false },
  { title: "Owner",      type: "TEXT_NUMBER", primary: false },
  { title: "Status",     type: "TEXT_NUMBER", primary: false },
  { title: "Notes",      type: "TEXT_NUMBER", primary: false },
] as const;

/** Build a column-name → column-ID map from a sheet's columns array. */
function buildColMap(columns: any[]): Record<string, number> {
  const map: Record<string, number> = {};
  for (const col of columns) {
    map[col.title] = col.id;
  }
  return map;
}

export interface TimelineTask {
  taskName: string;
  phase: string;
  startDate: string;
  endDate: string;
  durationDays: number;
  predecessors: string; // e.g. "1" or "1,2" — 1-based indices into the task list
  owner: string;
  status: string;
  notes: string;
}

export interface TimelineResult {
  sheetId: string;
  sheetUrl: string;
}

function getClient() {
  const key = getSmartsheetKey();
  if (!key) throw new Error("Smartsheet API key not configured");
  return smartsheetLib.createClient({ accessToken: key, logLevel: "info" });
}

/** Verify the API key by fetching the current user. Returns email on success. */
export async function verifySmartsheetConnection(): Promise<{ connected: boolean; email?: string; error?: string }> {
  try {
    const client = getClient();
    const result = await client.users.getCurrentUser({});
    const user = (result as any).data ?? result;
    return { connected: true, email: user.email };
  } catch (err: any) {
    return { connected: false, error: err?.message ?? "Unknown error" };
  }
}

/** Generate timeline tasks using the configured AI provider. */
export async function generateTimelineTasks(
  project: Project,
  settings: { provider?: string | null },
  supportingDocs: Array<{ name: string; content: string }> = []
): Promise<TimelineTask[]> {
  const prompt = buildTimelinePrompt(project, supportingDocs);

  let raw: string;
  if (settings.provider === "anthropic") {
    const key = getAnthropicKey();
    if (!key) throw new Error("Anthropic API key not configured");
    const client = new Anthropic({ apiKey: key, timeout: 60_000 });
    const msg = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }],
    });
    raw = (msg.content[0] as { type: string; text: string }).text;
  } else {
    const key = getOpenAIKey();
    if (!key) throw new Error("OpenAI API key not configured");
    const client = new OpenAI({ apiKey: key, timeout: 60_000 });
    const resp = await client.chat.completions.create({
      model: "gpt-5.2",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
    });
    raw = resp.choices[0].message.content ?? "{}";
  }

  return parseTasksFromResponse(raw);
}

function buildTimelinePrompt(project: Project, supportingDocs: Array<{ name: string; content: string }> = []): string {
  const milestones = (project.billingMilestones as { stage: string; percentage: number; date: string }[])
    .map((m) => `  - ${m.stage} (${m.percentage}%): ${m.date}`)
    .join("\n");
  const flipsideTeam = (project.flipsideStakeholders as { name: string; role: string }[])
    .map((s) => `  - ${s.name} (${s.role})`)
    .join("\n");
  const clientTeam = (project.clientStakeholders as { name: string; role: string }[])
    .map((s) => `  - ${s.name} (${s.role})`)
    .join("\n");

  // Use the full extracted text (already capped at 15,000 chars each by extractSupportingDocText)
  const supportingDocsSection = supportingDocs.length > 0
    ? `\nSupporting documents (use phases, tasks, and structure described here to inform your timeline):\n${supportingDocs.map((d) => `--- ${d.name} ---\n${d.content}`).join("\n\n")}\n`
    : "";

  return `You are a project management expert. Generate a detailed project timeline as a JSON object.

Project details:
- Name: ${project.projectName}
- Type: ${project.projectType}
- Size: ${project.projectSize}
- Start date: ${project.startDate}
- End date: ${project.endDate}
- Summary: ${project.summary}

Billing milestones (use as date anchors only — do NOT use as phase names):
${milestones}

Flipside team (internal — own delivery tasks):
${flipsideTeam}

Client team (own client-side tasks):
${clientTeam}
${supportingDocsSection}
Return a JSON object with a single key "tasks" containing an array. Tasks are numbered 1..N in order.
Each task must have exactly these fields:
{
  "taskName": "string (concise action-oriented task name)",
  "phase": "string (logical project phase name, e.g. 'Discovery', 'Design', 'Development', 'UAT', 'Go Live')",
  "startDate": "YYYY-MM-DD",
  "endDate": "YYYY-MM-DD",
  "durationDays": number,
  "predecessors": "string (comma-separated 1-based task numbers this task depends on, e.g. '1' or '2,3', or '' if none)",
  "owner": "string (first name only from the relevant team list, or 'TBC')",
  "status": "Not Started",
  "notes": "string (brief context, or empty string)"
}

Guidelines:
- Generate 15–30 tasks appropriate for a ${project.projectType} project of ${project.projectSize} size
- If supporting documents describe specific phases, workstreams or deliverables, reflect those in the task list and phase names
- Assign phases based on logical project stages (e.g. Discovery, Scoping, Design, Development, Content, Testing, UAT, Launch Prep, Go Live, Handover). Choose phases that fit a ${project.projectType} project — not all apply.
- Use the billing milestones as date anchors to ensure key deliverables land on or before milestone dates
- Owner assignment rules:
  * Flipside team members own: project management, design, development, UAT amend fixes, DevOps, delivery tasks
  * Client team members own: content provision, approvals, sign-off, UAT testing/execution, stakeholder reviews, client-side actions
  * Use first name only (e.g. "Tim", "Anthony") or a client first name; use 'TBC' only if genuinely unclear
- Tasks within a phase should appear in sequence; use predecessors to link dependent tasks
- The first task of each phase typically has no predecessor or depends on the last task of the previous phase
- Assign realistic start/end dates between ${project.startDate} and ${project.endDate}
- All dates must be in YYYY-MM-DD format
- Return only valid JSON, no markdown, no explanation`;
}

function parseTasksFromResponse(raw: string): TimelineTask[] {
  const cleaned = raw.replace(/^```(?:json)?\n?/m, "").replace(/\n?```$/m, "").trim();
  const parsed = JSON.parse(cleaned);
  const arr = Array.isArray(parsed) ? parsed : (parsed.tasks ?? []);
  return arr.map((t: Record<string, unknown>) => ({
    taskName: String(t.taskName ?? t.task_name ?? ""),
    phase: String(t.phase ?? ""),
    startDate: String(t.startDate ?? t.start_date ?? ""),
    endDate: String(t.endDate ?? t.end_date ?? ""),
    durationDays: Number(t.durationDays ?? t.duration_days ?? 0),
    predecessors: String(t.predecessors ?? t.predecessor ?? ""),
    owner: String(t.owner ?? "TBC"),
    status: String(t.status ?? "Not Started"),
    notes: String(t.notes ?? ""),
  }));
}

/**
 * Create a new timeline sheet in Smartsheet with Gantt settings and phase grouping.
 */
export async function createTimelineSheet(
  project: Project,
  tasks: TimelineTask[],
  workspaceId?: string | null
): Promise<TimelineResult> {
  const client = getClient();
  const sheetName = `${project.sheetRef} - ${project.projectName} Timeline`;

  const columns = COLUMNS.map((c) => ({ title: c.title, type: c.type, primary: c.primary }));

  let sheet: any;
  if (workspaceId) {
    sheet = await client.sheets.createSheetInWorkspace({
      workspaceId,
      body: { name: sheetName, columns },
    });
  } else {
    sheet = await client.sheets.createSheet({ body: { name: sheetName, columns } });
  }

  const numericSheetId: number = Number(sheet.result?.id ?? sheet.id);
  const sheetId: string = String(numericSheetId);

  // Fetch columns to build the name→id map
  const sheetDetails = await client.sheets.getSheet({ sheetId: numericSheetId });
  const colMap = buildColMap(sheetDetails.columns ?? []);

  // Write task rows grouped by phase with hierarchy
  await writeTaskRowsWithHierarchy(client, numericSheetId, colMap, tasks);

  const finalSheet = await client.sheets.getSheet({ sheetId: numericSheetId });
  const sheetUrl: string = finalSheet.permalink ?? `https://app.smartsheet.com/sheets/${sheetId}`;

  return { sheetId, sheetUrl };
}

/**
 * Update an existing timeline sheet, or recreate it if the column structure is
 * incompatible (e.g. old TEXT_NUMBER dates, missing Predecessor column).
 * Returns the sheet ID and URL — which may differ from the input if the sheet
 * was recreated.
 */
export async function upsertTimeline(
  existingSheetId: string,
  project: Project,
  tasks: TimelineTask[],
  workspaceId?: string | null
): Promise<TimelineResult> {
  const client = getClient();
  const numericSheetId = Number(existingSheetId);

  let sheet: any;
  try {
    sheet = await client.sheets.getSheet({ sheetId: numericSheetId });
  } catch (_) {
    // Sheet was deleted externally — create a fresh one
    return createTimelineSheet(project, tasks, workspaceId);
  }
  const columns: any[] = sheet.columns ?? [];
  const colMap = buildColMap(columns);

  // Detect old column structure: Start Date must be DATE type (not TEXT_NUMBER from older sheets)
  const startDateCol = columns.find((c: any) => c.title === "Start Date");
  const compatible = startDateCol?.type === "DATE";

  if (!compatible) {
    console.log(`[timeline] Sheet ${existingSheetId} has incompatible structure — deleting and recreating with Gantt support`);
    try { await client.sheets.deleteSheet({ sheetId: numericSheetId }); } catch (_) { /* orphaned sheet is fine */ }
    return createTimelineSheet(project, tasks, workspaceId);
  }

  // Compatible — delete all rows and rewrite
  const existingRows: any[] = sheet.rows ?? [];
  if (existingRows.length > 0) {
    const rowIds = existingRows.map((r: any) => r.id);
    for (let i = 0; i < rowIds.length; i += 450) {
      await client.sheets.deleteRows({
        sheetId: numericSheetId,
        queryParameters: { ids: rowIds.slice(i, i + 450) },
      });
    }
  }

  await writeTaskRowsWithHierarchy(client, numericSheetId, colMap, tasks);

  const permalink: string = sheet.permalink ?? `https://app.smartsheet.com/sheets/${existingSheetId}`;
  return { sheetId: existingSheetId, sheetUrl: permalink };
}

/**
 * Write tasks to the sheet with phase-header hierarchy (parentId).
 * Phase headers are bold parent rows; tasks are indented children underneath.
 *
 * Columns are looked up by name so order doesn't matter and extra Smartsheet-injected
 * columns (e.g. % Complete, Duration added when Gantt/dependencies are enabled) don't
 * cause misalignment.
 *
 * After all rows are written, the sheet is re-fetched to get the live column state
 * (Smartsheet may add/modify system columns after row operations), then predecessor
 * cells are updated with correct Smartsheet row numbers.
 */
async function writeTaskRowsWithHierarchy(
  client: ReturnType<typeof smartsheetLib.createClient>,
  sheetId: number,
  colMap: Record<string, number>,
  tasks: TimelineTask[]
): Promise<void> {
  if (tasks.length === 0) return;

  const cTask   = colMap["Task Name"];
  const cStart  = colMap["Start Date"];
  const cEnd    = colMap["End Date"];
  const cOwner  = colMap["Owner"];
  const cStatus = colMap["Status"];
  const cNotes  = colMap["Notes"];

  // Group tasks by phase, preserving order
  const phases: string[] = [];
  const tasksByPhase = new Map<string, TimelineTask[]>();
  for (const task of tasks) {
    if (!tasksByPhase.has(task.phase)) {
      phases.push(task.phase);
      tasksByPhase.set(task.phase, []);
    }
    tasksByPhase.get(task.phase)!.push(task);
  }

  // task 1-based index → { rowNumber, rowId } for predecessor pass
  const taskRowInfo = new Map<number, { rowNumber: number; rowId: number }>();
  let taskIndex = 0;

  // Write phase header rows then child task rows in hierarchy
  for (const phase of phases) {
    // Add bold phase header row
    const headerResult = await client.sheets.addRows({
      sheetId,
      body: [{
        toBottom: true,
        bold: true,
        cells: [{ columnId: cTask, value: phase }],
      }],
    });
    const headerRow = (headerResult.result ?? headerResult)[0];
    const headerRowId: number = headerRow.id;

    // Add task rows as children of the phase header
    const phaseTasks = tasksByPhase.get(phase)!;
    const taskBodies = phaseTasks.map((task) => ({
      parentId: headerRowId,
      toBottom: true,
      cells: [
        cTask   && { columnId: cTask,   value: task.taskName },
        cStart  && { columnId: cStart,  value: task.startDate },
        cEnd    && { columnId: cEnd,    value: task.endDate },
        cOwner  && { columnId: cOwner,  value: task.owner },
        cStatus && { columnId: cStatus, value: task.status },
        cNotes  && { columnId: cNotes,  value: task.notes },
      ].filter(Boolean),
    }));

    const taskResult = await client.sheets.addRows({ sheetId, body: taskBodies });
    const addedTaskRows: any[] = taskResult.result ?? taskResult;
    for (const row of addedTaskRows) {
      taskIndex++;
      taskRowInfo.set(taskIndex, { rowNumber: row.rowNumber, rowId: row.id });
    }
  }

  // Pass 2: re-fetch sheet to get live column state (Smartsheet may have added/changed
  // system columns like Predecessor after row operations)
  const freshSheet = await client.sheets.getSheet({ sheetId });
  const freshColMap = buildColMap(freshSheet.columns ?? []);
  const cPred = freshColMap["Predecessor"];

  if (!cPred) return; // dependencies not yet enabled — nothing to write

  const updates: any[] = [];
  let tIdx = 0;
  for (const task of tasks) {
    tIdx++;
    if (!task.predecessors) continue;

    const predValue = task.predecessors
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((idx) => taskRowInfo.get(Number(idx))?.rowNumber)
      .filter((n): n is number => n !== undefined)
      .join(",");

    if (!predValue) continue;
    const rowId = taskRowInfo.get(tIdx)?.rowId;
    if (!rowId) continue;

    updates.push({ id: rowId, cells: [{ columnId: cPred, value: predValue }] });
  }

  for (let i = 0; i < updates.length; i += 500) {
    await client.sheets.updateRow({ sheetId, body: updates.slice(i, i + 500) });
  }
}
