/**
 * Smartsheet integration service.
 *
 * Wraps the Smartsheet REST API (via smartsheet-javascript-sdk) to create and
 * update project timeline sheets. Timeline task rows are generated by calling
 * the configured AI provider (Anthropic or OpenAI).
 *
 * Sheet structure:
 *   - Phase header rows (parent, bold) group tasks visually
 *   - Task rows are children of their phase header
 *   - Columns: Task Name | Start Date | End Date | Duration (days) | Predecessor | Owner | Status | Notes
 *   - Project settings enable Gantt / dependency tracking
 */

import * as smartsheetLib from "smartsheet";
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { getSmartsheetKey, getAnthropicKey, getOpenAIKey } from "./secrets";
import type { Project } from "../shared/schema";

// Column definitions — order matters: indices are used in writeTaskRows
const COLUMNS = [
  { title: "Task Name",       type: "TEXT_NUMBER", primary: true  },
  { title: "Start Date",      type: "DATE",        primary: false },
  { title: "End Date",        type: "DATE",        primary: false },
  { title: "Duration (days)", type: "TEXT_NUMBER", primary: false },
  { title: "Predecessor",     type: "PREDECESSOR", primary: false },
  { title: "Owner",           type: "TEXT_NUMBER", primary: false },
  { title: "Status",          type: "TEXT_NUMBER", primary: false },
  { title: "Notes",           type: "TEXT_NUMBER", primary: false },
] as const;

// Column index constants
const COL = { TASK: 0, START: 1, END: 2, DUR: 3, PRED: 4, OWNER: 5, STATUS: 6, NOTES: 7 };

export interface TimelineTask {
  taskName: string;
  phase: string;
  startDate: string;
  endDate: string;
  durationDays: number;
  predecessors: string; // e.g. "1" or "1,2" — 1-based indices into the task list
  owner: string;
  status: string;
  notes: string;
}

export interface TimelineResult {
  sheetId: string;
  sheetUrl: string;
}

function getClient() {
  const key = getSmartsheetKey();
  if (!key) throw new Error("Smartsheet API key not configured");
  return smartsheetLib.createClient({ accessToken: key, logLevel: "info" });
}

/** Verify the API key by fetching the current user. Returns email on success. */
export async function verifySmartsheetConnection(): Promise<{ connected: boolean; email?: string; error?: string }> {
  try {
    const client = getClient();
    const result = await client.users.getCurrentUser({});
    const user = (result as any).data ?? result;
    return { connected: true, email: user.email };
  } catch (err: any) {
    return { connected: false, error: err?.message ?? "Unknown error" };
  }
}

/** Generate timeline tasks using the configured AI provider. */
export async function generateTimelineTasks(
  project: Project,
  settings: { provider?: string | null }
): Promise<TimelineTask[]> {
  const prompt = buildTimelinePrompt(project);

  let raw: string;
  if (settings.provider === "anthropic") {
    const key = getAnthropicKey();
    if (!key) throw new Error("Anthropic API key not configured");
    const client = new Anthropic({ apiKey: key, timeout: 60_000 });
    const msg = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }],
    });
    raw = (msg.content[0] as { type: string; text: string }).text;
  } else {
    const key = getOpenAIKey();
    if (!key) throw new Error("OpenAI API key not configured");
    const client = new OpenAI({ apiKey: key, timeout: 60_000 });
    const resp = await client.chat.completions.create({
      model: "gpt-5.2",
      messages: [{ role: "user", content: prompt }],
      response_format: { type: "json_object" },
    });
    raw = resp.choices[0].message.content ?? "{}";
  }

  return parseTasksFromResponse(raw);
}

function buildTimelinePrompt(project: Project): string {
  const milestones = (project.billingMilestones as { stage: string; percentage: number; date: string }[])
    .map((m) => `  - ${m.stage} (${m.percentage}%): ${m.date}`)
    .join("\n");
  const owners = (project.flipsideStakeholders as { name: string; role: string }[])
    .map((s) => `  - ${s.name} (${s.role})`)
    .join("\n");

  return `You are a project management expert. Generate a detailed project timeline as a JSON object.

Project details:
- Name: ${project.projectName}
- Type: ${project.projectType}
- Size: ${project.projectSize}
- Start date: ${project.startDate}
- End date: ${project.endDate}
- Summary: ${project.summary}

Billing milestones (use as phase anchors):
${milestones}

Team members available to assign as owners:
${owners}

Return a JSON object with a single key "tasks" containing an array. Tasks are numbered 1..N in order.
Each task must have exactly these fields:
{
  "taskName": "string (concise action-oriented task name)",
  "phase": "string (logical project phase name, e.g. 'Discovery', 'Design', 'Development', 'UAT', 'Go Live')",
  "startDate": "YYYY-MM-DD",
  "endDate": "YYYY-MM-DD",
  "durationDays": number,
  "predecessors": "string (comma-separated 1-based task numbers this task depends on, e.g. '1' or '2,3', or '' if none)",
  "owner": "string (first name only from the team list, or 'TBC')",
  "status": "Not Started",
  "notes": "string (brief context, or empty string)"
}

Guidelines:
- Generate 15–30 tasks appropriate for a ${project.projectType} project of ${project.projectSize} size
- Assign phases based on logical project stages for this type of project (e.g. Discovery, Scoping, Design, Development, Content, Testing, UAT, Launch Prep, Go Live, Handover). Choose phases that make sense for a ${project.projectType} project — not all phases apply to every project.
- Use the billing milestones as date anchors to ensure key deliverables land on or before milestone dates, but do NOT use milestone names as phase names
- Tasks within a phase should appear in sequence; use predecessors to link dependent tasks
- The first task of each phase typically has no predecessor or depends on the last task of the previous phase
- Assign realistic start/end dates between ${project.startDate} and ${project.endDate}
- Assign owners sensibly based on their role
- All dates must be in YYYY-MM-DD format
- Return only valid JSON, no markdown, no explanation`;
}

function parseTasksFromResponse(raw: string): TimelineTask[] {
  const cleaned = raw.replace(/^```(?:json)?\n?/m, "").replace(/\n?```$/m, "").trim();
  const parsed = JSON.parse(cleaned);
  const arr = Array.isArray(parsed) ? parsed : (parsed.tasks ?? []);
  return arr.map((t: Record<string, unknown>) => ({
    taskName: String(t.taskName ?? t.task_name ?? ""),
    phase: String(t.phase ?? ""),
    startDate: String(t.startDate ?? t.start_date ?? ""),
    endDate: String(t.endDate ?? t.end_date ?? ""),
    durationDays: Number(t.durationDays ?? t.duration_days ?? 0),
    predecessors: String(t.predecessors ?? t.predecessor ?? ""),
    owner: String(t.owner ?? "TBC"),
    status: String(t.status ?? "Not Started"),
    notes: String(t.notes ?? ""),
  }));
}

/**
 * Create a new timeline sheet in Smartsheet with Gantt settings and phase grouping.
 */
export async function createTimelineSheet(
  project: Project,
  tasks: TimelineTask[],
  workspaceId?: string | null
): Promise<TimelineResult> {
  const client = getClient();
  const sheetName = `${project.sheetRef} - ${project.projectName} Timeline`;

  const columns = COLUMNS.map((c) => ({ title: c.title, type: c.type, primary: c.primary }));

  let sheet: any;
  if (workspaceId) {
    sheet = await client.sheets.createSheetInWorkspace({
      workspaceId,
      body: { name: sheetName, columns },
    });
  } else {
    sheet = await client.sheets.createSheet({ body: { name: sheetName, columns } });
  }

  const numericSheetId: number = Number(sheet.result?.id ?? sheet.id);
  const sheetId: string = String(numericSheetId);

  // Fetch column IDs
  const sheetDetails = await client.sheets.getSheet({ sheetId: numericSheetId });
  const colIds: number[] = (sheetDetails.columns ?? []).map((c: any) => c.id);

  // Enable Gantt / dependency tracking
  await enableGanttSettings(client, numericSheetId);

  // Write task rows grouped by phase with hierarchy
  await writeTaskRowsWithHierarchy(client, numericSheetId, colIds, tasks);

  const finalSheet = await client.sheets.getSheet({ sheetId: numericSheetId });
  const sheetUrl: string = finalSheet.permalink ?? `https://app.smartsheet.com/sheets/${sheetId}`;

  return { sheetId, sheetUrl };
}

/**
 * Update an existing timeline sheet by replacing all data rows.
 */
export async function updateTimelineSheet(
  sheetId: string,
  tasks: TimelineTask[]
): Promise<void> {
  const client = getClient();
  const numericSheetId = Number(sheetId);

  const sheet = await client.sheets.getSheet({ sheetId: numericSheetId });
  const colIds: number[] = (sheet.columns ?? []).map((c: any) => c.id);
  const existingRows: any[] = sheet.rows ?? [];

  if (existingRows.length > 0) {
    const rowIds = existingRows.map((r: any) => r.id);
    for (let i = 0; i < rowIds.length; i += 450) {
      await client.sheets.deleteRows({
        sheetId: numericSheetId,
        queryParameters: { ids: rowIds.slice(i, i + 450) },
      });
    }
  }

  await writeTaskRowsWithHierarchy(client, numericSheetId, colIds, tasks);
}

/** Enable dependency tracking (Gantt) on the sheet. */
async function enableGanttSettings(
  client: ReturnType<typeof smartsheetLib.createClient>,
  numericSheetId: number
): Promise<void> {
  await client.sheets.updateSheet({
    sheetId: numericSheetId,
    body: {
      projectSettings: {
        nonWorkingDays: [],
        workingDays: [1, 2, 3, 4, 5],
        lengthOfDay: 8,
        useResourceAllocation: false,
      },
    },
  });
}

/**
 * Write tasks to the sheet grouped into phase header rows (parents) with tasks as children.
 * After all rows are written, predecessor cells are updated with correct row numbers.
 */
async function writeTaskRowsWithHierarchy(
  client: ReturnType<typeof smartsheetLib.createClient>,
  sheetId: number,
  colIds: number[],
  tasks: TimelineTask[]
): Promise<void> {
  if (tasks.length === 0) return;

  // Group tasks by phase, preserving order
  const phases: string[] = [];
  const tasksByPhase = new Map<string, TimelineTask[]>();
  for (const task of tasks) {
    if (!tasksByPhase.has(task.phase)) {
      phases.push(task.phase);
      tasksByPhase.set(task.phase, []);
    }
    tasksByPhase.get(task.phase)!.push(task);
  }

  // Maps task's 1-based index (position in `tasks` array) to its Smartsheet row number
  const taskIndexToRowNumber = new Map<number, number>();
  // Track (taskIndex → rowId) for predecessor updates
  const taskIndexToRowId = new Map<number, number>();
  let taskIndex = 0; // 1-based counter across all tasks

  for (const phase of phases) {
    const phaseTasks = tasksByPhase.get(phase)!;

    // 1. Add the phase header row
    const headerResult = await client.sheets.addRows({
      sheetId,
      body: [{
        toBottom: true,
        bold: true,
        cells: [{ columnId: colIds[COL.TASK], value: phase }],
      }],
    });
    const headerRows: any[] = headerResult.result ?? headerResult;
    const headerRowId: number = headerRows[0].id;

    // 2. Add task rows as children of the header
    const taskRowBodies = phaseTasks.map((task) => ({
      parentId: headerRowId,
      toBottom: true,
      cells: [
        { columnId: colIds[COL.TASK],   value: task.taskName },
        { columnId: colIds[COL.START],  value: task.startDate },
        { columnId: colIds[COL.END],    value: task.endDate },
        { columnId: colIds[COL.DUR],    value: task.durationDays },
        // Predecessor written in pass 2; leave blank for now
        { columnId: colIds[COL.OWNER],  value: task.owner },
        { columnId: colIds[COL.STATUS], value: task.status },
        { columnId: colIds[COL.NOTES],  value: task.notes },
      ].filter((_, i) => colIds[i] !== undefined),
    }));

    // Add in batches of 500
    for (let i = 0; i < taskRowBodies.length; i += 500) {
      const addedResult = await client.sheets.addRows({
        sheetId,
        body: taskRowBodies.slice(i, i + 500),
      });
      const addedRows: any[] = addedResult.result ?? addedResult;
      addedRows.forEach((row: any, batchOffset: number) => {
        const tIdx = taskIndex + i + batchOffset + 1; // 1-based
        taskIndexToRowNumber.set(tIdx, row.rowNumber);
        taskIndexToRowId.set(tIdx, row.id);
      });
    }

    taskIndex += phaseTasks.length;
  }

  // Pass 2: update predecessor cells for tasks that have predecessors
  const predecessorUpdates: any[] = [];
  let tIdx = 0;
  for (const task of tasks) {
    tIdx++;
    if (!task.predecessors) continue;

    const predRowNumbers = task.predecessors
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean)
      .map((idx) => taskIndexToRowNumber.get(Number(idx)))
      .filter((n): n is number => n !== undefined);

    if (predRowNumbers.length === 0) continue;

    const predValue = predRowNumbers.join(",");
    const rowId = taskIndexToRowId.get(tIdx);
    if (!rowId) continue;

    predecessorUpdates.push({
      id: rowId,
      cells: [{ columnId: colIds[COL.PRED], value: predValue }],
    });
  }

  if (predecessorUpdates.length > 0) {
    for (let i = 0; i < predecessorUpdates.length; i += 500) {
      await client.sheets.updateRow({
        sheetId,
        body: predecessorUpdates.slice(i, i + 500),
      });
    }
  }
}
